Login Form
K-Zama/ruralmondo-frontend pull request #2
Opened 2020-07-15 18:29 UTC by K-Zama

2020-07-15 18:32 UTC, avegao requested changes

2020-07-15 18:32 UTC, avegao commented on css/style.css
> +
Si no lo vas a usar no lo pongas

2020-07-15 18:32 UTC, avegao commented on index.html
> +    <link rel="stylesheet" href="./css/style.css">
Quítale el punto, luego en el server va a dar problemas y con el local server ya te tira bien en local.

2020-07-15 18:32 UTC, avegao commented on index.html
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossori
Actualiza Bootstrap

2020-07-15 18:32 UTC, avegao commented on index.html
> +    <title>Dashboard</title>
Pon el title correcto de esta página

2020-07-15 18:32 UTC, avegao commented on index.html
> +    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></
Actualiza Bootstrap

2020-07-15 18:32 UTC, avegao commented on index.html
> +    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></
Y revisa también jQuery y el popper

2020-07-16 08:41 UTC, K-Zama commented
Done!

2020-07-16 10:38 UTC, avegao requested changes
Más comentario

2020-07-16 10:38 UTC, avegao commented on index.html
> +    <title>Login</title>
Esto mejor si pones Ruralmondo - NOMBREPAGINA

2020-07-16 10:38 UTC, avegao commented on index.html
> +                <form>
El form de bootstap no tiene una clase? Creo que aqui te falta algo

2020-07-16 11:15 UTC, avegao commented on index.html
> +                <form>
Ya he visto que no, antiguamente si hacía falta

2020-07-16 11:16 UTC, avegao commented on index.html
> +    <title>Login</title>
Esto no lo has cambiado aunque el título de commit diga lo contrario

2020-07-16 11:37 UTC, avegao requested changes

2020-07-16 11:37 UTC, avegao commented on index.html
> +    <title>Ruralmondo-Login</title>
Separado!

2020-07-17 10:42 UTC, avegao requested changes
Tienes comentarios

2020-07-17 10:42 UTC, avegao commented on js/app.js
> +        const bienvenida = document.createElement("h5");
Los nombres en inglés

2020-07-17 10:42 UTC, avegao commented on js/app.js
> +        bienvenida.innerHTML = `¡Coge tu 9 de Airshoft con cañón turcao!`;
Aquí tienes una errata

2020-07-17 10:42 UTC, avegao commented on js/app.js
> +const formularioLogin = document.querySelector("#formularioLogin");
Las variables en inglés y lo mismo con las clases y los ids de HTML o CSS, **siempre** todo en inglés. Menos los textos lógicamente.

2020-07-17 11:36 UTC, avegao requested changes

2020-07-17 11:36 UTC, avegao commented on js/app.js
> +        wellcome.innerHTML = `¡Coge tu 9 de Airshoft con cañón turcao!`;
La errata no la has corregido

2020-07-17 11:51 UTC, K-Zama commented on js/app.js
> +        wellcome.innerHTML = `¡Coge tu 9 de Airshoft con cañón turcao!`;
Está escrito así a posta, luego te digo de donde viene. Es una tontería que se que les va a hacer gracia, por eso lo he puesto

2020-07-17 11:53 UTC, avegao approved these changes

2020-07-17 11:53 UTC, merged